export default {
  '/admin': 'Home',
  // '/admin/dashboard': 'Dashboard',
  '/admin/orders': 'Orders',
  '/admin/orders/view': 'View Orders',
  '/admin/orders/new': 'New Order',
  '/admin/orders/edit': 'Edit Order',
  '/admin/users': 'Users',
  '/admin/users/view': 'View Users',
  '/admin/users/new': 'New User',
  '/admin/users/edit': 'Edit User',
  '/admin/users/reset-password': 'Reset Password',
  '/admin/clients': 'Clients',
  '/admin/clients/view': 'View Clients',
  '/admin/clients/new': 'New Clinet',
  '/admin/clients/edit': 'Edit Clinet',
  '/admin/plans': 'Plans',
  '/admin/plans/view': 'View Plans',
  '/admin/plans/new': 'New Plan',
  '/admin/plans/edit': 'Edit Plan',
  '/admin/balances': 'Balances',
  '/admin/balances/view': 'View Balances',
  '/admin/balances/new': 'New Balance',
  '/admin/reports/sales': 'Sales Report'
};
